### ISSUE TITLE
recipe for diamond and emerald generators is not working

### ISSUE THREAD

**Issue by demonicreaper666** [JDKDigital/cobblegengalore#1]
{
  "type": "minecraft:crafting_shaped",
  "category": "misc",
  "key": {
    "G": {
      "item": "minecraft:glass"
    },
    "R": {
  * *  **  "tag": "c:ingots/diamond" ** --- Error lies with this tag. its the same issue with the emerald one.* * 
    }
  },
  "pattern": [
    "RRR",
    "G G",
    "RRR"
  ],
  "result": {
    "id": "cobblegengalore:block_gen_diamond"
  }
}

I think you figured out the issue from above but if not Emeralds and Diamonds are gems not ingots. so the tag needed would be c:gems/diamond && c:gems/emerald respectively

also might be a seperate issue, the blocks have no correct tool for drops, and take forever to break, unless this is intended

**Comment by JaisDK** [comment]
are you on the latest version?

**Comment by demonicreaper666** [comment]
the version released on 9/24/2024 - version 1.21.1-0.1.0, its the only one currently listed on curseforge app. neo version is 21.1.61 (direwolf20 pack)

**Comment by demonicreaper666** [comment]
imma gonna say it is a curse issue, as I see you already fixed the issue on your end. I will use kubejs to add a custom datapack until curse decides to give the update.
Thank you.

**Comment by JaisDK** [comment]
no I fixed the same thing in another mod because I thought you meant that one, I'll upload a fix for this one in a minute

**Comment by demonicreaper666** [comment]
thank you and glad i could help you fix the other mod unintentionally.

Again Thank you.
