### ISSUE TITLE
Generation speed by tiers

### ISSUE THREAD

**Issue by kaiserdj** [JDKDigital/cobblegengalore#4]
Hi, it is assumed that depending on the tier of machine you build it goes faster but in all of them it generates at the same rate. At least in the ATM10 mod pack which has the default configuration.

https://github.com/user-attachments/assets/770a6e81-c53d-454e-ba63-906f92949b66

**Comment by JaisDK** [comment]
when you use fluid source blocks it can only consume one at a time, use a fluid container instead like a tank with water (maybe the sink will work too)

**Comment by kaiserdj** [comment]
You're right, it worked.
